; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[otrec][download][type] = ""
;projects[otrec][download][url] = ""
;projects[otrec][type] = "profile"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0-beta4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.0"

projects[cas][subdir] = "contrib"
projects[cas][version] = "1.1"

projects[composer_manager][subdir] = "contrib"
projects[composer_manager][version] = "1.6"

projects[date][subdir] = "contrib"
projects[date][version] = "2.7"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.2"

projects[domain][subdir] = "contrib"
projects[domain][version] = "3.11"

projects[domain_admin][subdir] = "contrib"
projects[domain_admin][version] = "1.0-beta1"

projects[domain_block_title][subdir] = "contrib"
projects[domain_block_title][version] = "1.0"

projects[domain_blocks][subdir] = "contrib"
projects[domain_blocks][version] = "3.0-beta1"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][version] = "2.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.1"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0-beta1"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0-rc2"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-unstable3"

projects[flippy][subdir] = "contrib"
projects[flippy][version] = "1.3"

projects[gss][subdir] = "contrib"
projects[gss][version] = "1.11"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-unstable3"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.6"

projects[nodeblock][subdir] = "contrib"
projects[nodeblock][version] = "1.2"

projects[page_theme][subdir] = "contrib"
projects[page_theme][version] = "1.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[pdx_wysiwyg_profiles][download][type] = ""
;projects[pdx_wysiwyg_profiles][download][url] = ""
;projects[pdx_wysiwyg_profiles][type] = "module"
;projects[pdx_wysiwyg_profiles][subdir] = "custom/otrec-cms"
;projects[pdx_wysiwyg_profiles][version] = "1.0"


projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.0"

projects[social-share][subdir] = "contrib"
projects[social-share][version] = "2.1"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0-rc1"

projects[tagclouds][subdir] = "contrib"
projects[tagclouds][version] = "1.9"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0"

projects[twitter_block][subdir] = "contrib"
projects[twitter_block][version] = "2.1"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.3"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0-rc1"

; Themes
projects[zen][version] = "5.4"

; Modules
projects[research-modules][type] = "module"
projects[research-modules][download][type] = "git"
projects[research-modules][download][url] = "git@github.com:/PSU-OIT-ARC/research-modules.git"

projects[otrec-cms][subdir] = "custom"
projects[otrec-cms][type] = "module"
projects[otrec-cms][download][type] = "git"
projects[otrec-cms][download][url] = "git@github.com:PSU-OIT-ARC/otrec-cms.git"

; Themes
projects[otrec_subtheme][type] = "theme"
projects[otrec_subtheme][download][type] = "git"
projects[otrec_subtheme][download][url] = "git@github.com:PSU-OIT-ARC/otrec_subtheme.git"

projects[nitc_subtheme][type] = "theme"
projects[nitc_subtheme][download][type] = "git"
projects[nitc_subtheme][download][url] = "git@github.com:PSU-OIT-ARC/otrec_subtheme.git"
projects[nitc_subtheme][download][branch] = "nitc_subtheme"

projects[psu_research_theme][type] = "theme"
projects[psu_research_theme][download][type] = "git"
projects[psu_research_theme][download][url] = "git@github.com:PSU-OIT-ARC/research-theme.git"

; Libraries
libraries[CAS][download][type] = "get"
libraries[CAS][download][url] = "http://downloads.jasig.org/cas-clients/php/current/CAS-1.3.3.tgz"
libraries[CAS][directory_name] = "CAS"
libraries[CAS][type] = "library"

libraries[chosen][download][type] = "get"
libraries[chosen][download][url] = "https://github.com/harvesthq/chosen/releases/download/v1.3.0/chosen_v1.3.0.zip"
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library

libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "http://download.moxiecode.com/tinymce/tinymce_4.1.7.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

